ALTER TABLE gymies_plans
  ADD COLUMN slug VARCHAR(32) NOT NULL DEFAULT '' COMMENT 'starter pro studio',
  ADD COLUMN description VARCHAR(500) DEFAULT NULL,
  ADD COLUMN max_sessions_per_month INT UNSIGNED DEFAULT NULL,
  ADD COLUMN max_trainer_accounts INT UNSIGNED DEFAULT 1,
  ADD COLUMN has_invoicing TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN has_crm TINYINT(1) NOT NULL DEFAULT 0,
  ADD COLUMN has_womens_choice TINYINT(1) NOT NULL DEFAULT 1,
  ADD COLUMN is_active TINYINT(1) NOT NULL DEFAULT 1;
